version: '3.4'

services:
  freakyfashionservices.gateway:
    image: ${DOCKER_REGISTRY-}freakyfashionservicesgateway
    build:
      context: .
      dockerfile: FreakyFashionServices.Gateway/Dockerfile

  freakyfashionservices.basket:
    image: ${DOCKER_REGISTRY-}freakyfashionservicesbasket
    build:
      context: .
      dockerfile: FreakyFashionServices.Basket/Dockerfile
  redis:
    image: redis

  freakyfashionservices.catalog:
    image: ${DOCKER_REGISTRY-}freakyfashionservicescatalog
    build:
      context: .
      dockerfile: FreakyFashionServices.Catalog/Dockerfile

  freakyfashionservices.order:
    image: ${DOCKER_REGISTRY-}freakyfashionservicesorder
    build:
      context: .
      dockerfile: FreakyFashionServices.Order/Dockerfile

  freakyfashionservices.productprice:
    image: ${DOCKER_REGISTRY-}freakyfashionservicesproductprice
    build:
      context: .
      dockerfile: FreakyFashionServices.ProductPrice/Dockerfile

        